### ISSUE TITLE
Connection refused @ storm.kafka.KafkaUtils.getOffset(KafkaUtils.java:57)

### ISSUE THREAD

**Issue by scarlett-ry** [wurstmeister/storm-kafka-0.8-plus-test#7]
Hi, sorry to put the question here, as i cannot find any clue from the internet.
When i run the KafkaSpoutTestTopology in eclipse, it quits with the Connetion refused message.
But it is ok to use the kafka consumer tool.
[root@yn1 kafka_2.10-0.8.2.1]# bin/kafka-console-consumer.sh --zookeeper localhost:2181 --from-beginning --topic mytest
[2015-04-30 15:00:51,977] INFO Closing socket connection to /127.0.0.1. (kafka.network.Processor)
hello world
hello asia
.....

I changed slightly to pass in the actual topic and zookeeper info.
    public StormTopology buildTopology() {
        SpoutConfig kafkaConfig = new SpoutConfig(brokerHosts, "mytest", "", "storm");
        kafkaConfig.scheme = new SchemeAsMultiScheme(new StringScheme());
        TopologyBuilder builder = new TopologyBuilder();
        builder.setSpout("words", new KafkaSpout(kafkaConfig), 10);
        builder.setBolt("print", new PrinterBolt()).shuffleGrouping("words");
        return builder.createTopology();
    }

```
public static void main(String[] args) throws Exception {

    //String kafkaZk = args[0];//"10.1.110.24:2181,10.1.110.22:2181" Zookeeper host:port list 
    String kafkaZk ="147.128.123.80:2181";
```

...... left is the same with original code.

Could someone help me to find why it failed to connect?

17582 [Thread-10-words] INFO storm.kafka.KafkaUtils - Task [1/1] assigned [Partition{host=localhost:9092, partition=0}]
17582 [Thread-10-words] INFO storm.kafka.ZkCoordinator - Task [1/1] Deleted partition managers: []
17582 [Thread-10-words] INFO storm.kafka.ZkCoordinator - Task [1/1] New partition managers: [Partition{host=localhost:9092, partition=0}]
17699 [Thread-10-words] INFO storm.kafka.PartitionManager - Read partition information from: /storm/partition_0 --> null
18762 [Thread-10-words] ERROR backtype.storm.util - Async loop died!
java.lang.RuntimeException: java.net.ConnectException: Connection refused: connect
    at storm.kafka.ZkCoordinator.refresh(ZkCoordinator.java:85)
    at storm.kafka.ZkCoordinator.getMyManagedPartitions(ZkCoordinator.java:52)
    at storm.kafka.KafkaSpout.nextTuple(KafkaSpout.java:118)
    at backtype.storm.daemon.executor$fn__3373$fn__3388$fn__3417.invoke(executor.clj:565)
    at backtype.storm.util$async_loop$fn__464.invoke(util.clj:463)
    at clojure.lang.AFn.run(AFn.java:24)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.net.ConnectException: Connection refused: connect
    at sun.nio.ch.Net.connect0(Native Method)
    at sun.nio.ch.Net.connect(Net.java:465)
    at sun.nio.ch.Net.connect(Net.java:457)
    at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:670)
    at kafka.network.BlockingChannel.connect(BlockingChannel.scala:57)
    at kafka.consumer.SimpleConsumer.connect(SimpleConsumer.scala:44)
    at kafka.consumer.SimpleConsumer.getOrMakeConnection(SimpleConsumer.scala:129)
    at kafka.consumer.SimpleConsumer.kafka$consumer$SimpleConsumer$$sendRequest(SimpleConsumer.scala:69)
    at kafka.consumer.SimpleConsumer.getOffsetsBefore(SimpleConsumer.scala:125)
    at kafka.javaapi.consumer.SimpleConsumer.getOffsetsBefore(SimpleConsumer.scala:80)
    at storm.kafka.KafkaUtils.getOffset(KafkaUtils.java:57)
    at storm.kafka.KafkaUtils.getOffset(KafkaUtils.java:47)
    at storm.kafka.PartitionManager.<init>(PartitionManager.java:76)
    at storm.kafka.ZkCoordinator.refresh(ZkCoordinator.java:80)
    ... 6 more
18763 [Thread-10-words] ERROR backtype.storm.daemon.executor - 
java.lang.RuntimeException: java.net.ConnectException: Connection refused: connect
    at storm.kafka.ZkCoordinator.refresh(ZkCoordinator.java:85)
    at storm.kafka.ZkCoordinator.getMyManagedPartitions(ZkCoordinator.java:52)
    at storm.kafka.KafkaSpout.nextTuple(KafkaSpout.java:118)
    at backtype.storm.daemon.executor$fn__3373$fn__3388$fn__3417.invoke(executor.clj:565)
    at backtype.storm.util$async_loop$fn__464.invoke(util.clj:463)
    at clojure.lang.AFn.run(AFn.java:24)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.net.ConnectException: Connection refused: connect
    at sun.nio.ch.Net.connect0(Native Method)
    at sun.nio.ch.Net.connect(Net.java:465)
    at sun.nio.ch.Net.connect(Net.java:457)
    at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:670)
    at kafka.network.BlockingChannel.connect(BlockingChannel.scala:57)
    at kafka.consumer.SimpleConsumer.connect(SimpleConsumer.scala:44)
    at kafka.consumer.SimpleConsumer.getOrMakeConnection(SimpleConsumer.scala:129)
    at kafka.consumer.SimpleConsumer.kafka$consumer$SimpleConsumer$$sendRequest(SimpleConsumer.scala:69)
    at kafka.consumer.SimpleConsumer.getOffsetsBefore(SimpleConsumer.scala:125)
    at kafka.javaapi.consumer.SimpleConsumer.getOffsetsBefore(SimpleConsumer.scala:80)
    at storm.kafka.KafkaUtils.getOffset(KafkaUtils.java:57)
    at storm.kafka.KafkaUtils.getOffset(KafkaUtils.java:47)
    at storm.kafka.PartitionManager.<init>(PartitionManager.java:76)
    at storm.kafka.ZkCoordinator.refresh(ZkCoordinator.java:80)
    ... 6 more
18790 [Thread-10-words] ERROR backtype.storm.util - Halting process: ("Worker died")
java.lang.RuntimeException: ("Worker died")
    at backtype.storm.util$exit_process_BANG_.doInvoke(util.clj:325)
    at clojure.lang.RestFn.invoke(RestFn.java:423)
    at backtype.storm.daemon.worker$fn__3808$fn__3809.invoke(worker.clj:452)
    at backtype.storm.daemon.executor$mk_executor_data$fn__3274$fn__3275.invoke(executor.clj:240)
    at backtype.storm.util$async_loop$fn__464.invoke(util.clj:473)
    at clojure.lang.AFn.run(AFn.java:24)
    at java.lang.Thread.run(Thread.java:744)

**Comment by scarlett-ry** [comment]
Hello, finally it is resolved.
The rootcause is that someone changed kafka server.properties to only bind localhost:
host.name=localhost

After I comment this line out, the error became:
 Caused by: java.nio.channels.UnresolvedAddressException

Then I add the host information in my win7 hosts file according to previous posts, the connection is ok.

Sorry and thanks.
